version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: local-postgres1
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
